### ISSUE TITLE
[BUG] - mouse over debug console

### ISSUE THREAD

**Issue by duzenko** [alefragnani/vscode-delphi-themes#10]
**Environment/version**

- Extension version: latest
- VSCode version: laatest
- OS version: win10

![image](https://user-images.githubusercontent.com/1481807/229508414-d8a978c7-fc75-4e23-b827-ad93388c098c.png)

**Comment by alefragnani** [comment]
Hi @duzenko ,

Please, could you please provide more details?

Thank you

**Comment by duzenko** [comment]
Lines in the debug console window change background color to blue on mouse hover
Expected: no color change or slight text color change (no background color change in any case)

**Comment by duzenko** [comment]
@alefragnani Thank you so much for accepting my suggestions. Any feedback? Issues?

**Comment by alefragnani** [comment]
You're welcome! Everything working just fine 👍
